[tool.poetry]
name = "hijabdetect-backend"
version = "0.1.0"
description = "Hijab Detection API"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.115.0"
uvicorn = "0.38.0"
ultralytics = "8.3.211"
pillow = "11.3.0"
python-multipart = "0.0.7"
# Loosen numpy version to avoid conflicts
numpy = ">=1.23,<1.27"
# Keep opencv-python compatible with the numpy range
opencv-python = ">=4.12.0,<4.14.0"
torch = "2.8.0"
torchvision = "0.15.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
